version: '3'
services:
  database:
    image: postgres:16.3
    expose:
      - 5432
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./configs/.psql.env

  service:
    build: app
    env_file:
      - path: ./app/.env
        required: true
    environment:
      - DEBUG=true
    expose:
      - 8000
    volumes:
      - static-data:/vol/static
    depends_on:
      - database

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static-data:/vol/static
    depends_on:
      - service
      - database
    ports:
      - "80:80"

volumes:
  static-data:
