# Generated by Django 5.0.6 on 2024-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_update_filmwork"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("movie", "movie"), ("tv_show", "tv_show")],
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"), name="unique_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "person", "role"), name="unique_person_role"
            ),
        ),
    ]
